# Generated by Django 2.2.14 on 2020-07-25 14:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(verbose_name='YouTube Link'),
        ),
    ]
