# Generated by Django 2.2.14 on 2020-07-25 17:09

import autoslug.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200725_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('created_at__month',)),
        ),
    ]
