# Generated by Django 2.2.14 on 2020-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200725_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='description',
            field=models.TextField(),
        ),
    ]
